---
measurement_settings:
  comment_en: False       # True prompts user input session comment.
  dark_mode_plot: True    # True saves plots in dark mode palette.
  in_cal_file_id: 1       # decides which calibration file to use.
  instr_buffer_time: 0.3  # seconds to wait between isntr commands.
  inter_freq_factor: 8    # multiplier factor from sig gen.
  is_calibration: True    # enables calibration handling.
  lnas_per_chain: 0       # how many lnas per chain?
  order: 1                # leave as 1 unless explicitly known why.
  project_title: 'Sig Gen Test'   # becomes folder title.
  psu_safe_init: True
  stage_1_2_same: False   # if True l1s1: l1s2 and l2s1: l2s2
  stage_2_3_same: False   # if True l1s2: l1s3 and l2s2: l2s3
  stages_per_lna: 0       # how many stages per lna?
  # for measure_method:
  # allcoldtoallhot: 'ACTAH', manualentrymeasure: 'MEM',
  # alternatingtemps: 'AT',  calibration: 'Calibration'
  measure_method: 'Calibration'  # chooses the measurement algorithm.

lna_ids:
  chain_1_lna_1_id: 21     # lna id number for 1st lna in chain 1.
  chain_1_lna_2_id: 25     # lna id number for 2nd lna in chain 1.
  chain_2_lna_1_id: 52     # lna id number for 1st lna in chain 2.
  chain_2_lna_2_id: 53     # lna id number for 2nd lna in chain 2.
  chain_3_lna_1_id: 54     # lna id number for 1st lna in chain 3.
  chain_3_lna_2_id: 55     # lna id number for 2nd lna in chain 3.
  
bias_sweep_settings:
  alt_temp_sweep_skips: 0  # num of meas to skip on 'at' alg sweep.
  chain_sequence:          # order of cryostat chains to measure.
    - 2 
  lna_sequence:            # [firstlnatosweep, secondlnatosweep].
    - 1
  stage_sequence:          # which order to sweep stages in.
    - 1
    - 2
  d_i_max: 5               # ma
  d_i_min: 5               # ma
  d_i_nominal: 6.0         # ma
  d_v_max: 1             # v
  d_v_min: 0.8             # v
  d_v_nominal: 0.9         # v
  num_of_d_i: 1            # v
  num_of_d_v: 2            # v
  
bias_psu_settings:
  d_i_lim: 10            # ma
  g_v_low_lim: -0.25     # v
  g_v_up_lim: +0.25      # v
  num_g_v_brd_steps: 5   # broad steps
  num_g_v_mid_steps: 5   # mid steps
  num_g_v_nrw_steps: 5   # narrow steps
  v_step_lim: 0.3        # v
  
signal_analyser_settings:
  atten: 10           # db
  center_freq: 0.075  # ghz
  freq_span: 25       # mhz
  marker_freq: 0.075  # ghz
  power_bw: 24        # mhz
  ref_level: -20      # dbm
  res_bw: 8           # mhz
  vid_bw: 10          # hz
  
signal_generator_settings:
  freq_step_size: 0.2      # ghz
  max_freq: 116          # ghz
  min_freq: 67           # ghz
  vna_or_sig_gen: 'sig gen'  # either 'vna' or 'sig gen'
  
temperature_controller_settings:
  # sensor channel variables named in format:
  # lakeshore_chain1/2/3/all_lna/load_channel
  allchn_load_lsch: '08'
  chn1_lna_lsch: '07'
  chn2_lna_lsch: '10'
  chn3_lna_lsch: '09'
  extra_sensors_en: False
  t_cold_target: 20.2    # kelvin - to give 20k
  t_hot_target: 50.9     # 60.9k - to give 60k
  
back_end_lna_settings: # cryo/room-temp_backend_all/chain#_drain_voltage/current
  be_d_i_limit: 20       # ma
  use_g_v_or_d_i: 'd i'  # Either 'd i' or 'g v'
  correct_be_d_v: False  # Whether to correct dv for wire voltage drop
  
  crbe_chn1_d_v: 1.2    # v
  crbe_chn1_d_i: 12    # ma
  crbe_chn1_g_v: 0.193   # v
  
  crbe_chn2_d_v: 1.21       # v
  crbe_chn2_d_i: 12.2     # ma
  crbe_chn2_g_v: 0.216    # v
  
  crbe_chn3_d_v: 1.25    # v
  crbe_chn3_d_i: 16.5    # ma
  crbe_chn3_g_v: 0.15    # v
  
  rtbe_chna_d_v: 1.22    # v
  rtbe_chna_d_i: 16      # ma
  rtbe_chna_g_v: -0.178  # v

manual_entry_lna_settings: # manual_lna#_stage#_drain_voltage/current
  man_l1_s1_d_v: 1    # v
  man_l1_s1_d_i: 6    # ma
  man_l1_s2_d_v: 1    # v
  man_l1_s2_d_i: 6    # ma
  man_l1_s3_d_v: 1.1  # v
  man_l1_s3_d_i: 6    # ma
  
  man_l2_s1_d_v: 1.2  # v
  man_l2_s1_d_i: 8    # ma
  man_l2_s2_d_v: 1.2  # v
  man_l2_s2_d_i: 8    # ma
  man_l2_s3_d_v: 1.1  # v
  man_l2_s3_d_i: 6    # ma

analysis_bandwidths:
  ana_bw_1_min_max: 
    - 67 # Min GHz
    - 90 # Max GHz  
  ana_bw_2_min_max:
    - 90 # Min GHz
    - 116 # Max GHz
  ana_bw_3_min_max: [] # If not required then []
  ana_bw_4_min_max: [] # If not required then []
  ana_bw_5_min_max: [] # If not required then []

available_instruments:
  bias_psu_en: True
  sig_an_en: True
  sig_gen_en: True
  switch_en: True
  temp_ctrl_en: True